name: ExpatOnlineCoaching
favicon: null
layout_spectrum: 0.23866269923746586
typography_spectrum: 0.11308164312504232
title: Expat Online Coaching
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-54184065-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fbfbfb'
    - '#b0b0b0'
    - '#868686'
    - '#414141'
  brandStrength: 0.4375
  lightness: 0.6705894628539681
  saturation: 0.4014694781508297
  rhythmicContrast: 0.16519285109825432
purpose: []
